#!/bin/bash

rofi_command="rofi -theme styles/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown="襤"
reboot="勒"
lock=""
suspend="⏾"
logout=""
sleep="鈴"

# Variable passed to rofi
options="$shutdown
$reboot
$lock
$suspend
$logout
$sleep"
_msg="Options  -  yes / y / no / n"

chosen="$(echo "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in $shutdown)
		ans=$($HOME/.config/rofi/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        systemctl poweroff
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/styles/askpass.rasi -e "$_msg"
        fi
        ;;
    $reboot)
		ans=$($HOME/.config/rofi/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
			if grep -q "Arch Linux" /etc/os-release
        			then
				systemctl reboot
			elif grep -q "void" /etc/os-release
			then
				reboot
			fi
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/styles/askpass.rasi -e "$_msg"
        fi
        ;;
    $lock)
        betterlockscreen -l
        ;;
    $suspend)
		ans=$($HOME/.config/rofi/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        mpc -q pause
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/styles/askpass.rasi -e "$_msg"
        fi
        ;;
    $logout)
		ans=$($HOME/.config/rofi/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        bspc quit
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/styles/askpass.rasi -e "$_msg"
        fi
        ;;
    $sleep)
		ans=$($HOME/.config/rofi/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        if grep -q "Arch Linux" /etc/os-release
        			then
				systemctl suspend
			elif grep -q "void" /etc/os-release
			then
				zzz
			fi
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        #rofi -theme ~/.config/rofi/styles/askpass.rasi -e "$_msg"
        fi
        ;;
esac

        
