#! /bin/bash
source ~/.config/colors

execute_exists() {
    # check if command exists and fail otherwise
    command -v "$1" >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
        return 0;
    else
        $1 &
    fi
}

bspc monitor -d '1' '2' '3' '4' '5'

bspc config border_width         	1
bspc config window_gap          	10
bspc config split_ratio          	10
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true

bspc config normal_border_color "$normal_borders"
bspc config focused_border_color "$focused_borders"

xsetroot -cursor_name left_ptr

# === KILL PROCESS 
 
pkill sxhkd 
pkill xfsettingsd 
pkill dunst 
pkill polybar 
pkill nitrogen 
pkill picom
pkill nitrogen
pkill gnome-keyring-daemon
pkill powerkit
pkill xfce4-power-manager

execute_exists sxhkd
execute_exists xfsettingsd
execute_exists xfce4-power-manager
execute_exists powerkit
execute_exists $HOME/.config/polybar/launch.sh
execute_exists dunst
#execute_exists picom

# === Clean Thumbnails
rm -rf ~/.cache/thumbnails/normal/*

# == Keyring 
gnome-keyring-daemon -f &

# === ABNT_KEY_BR
bash -c $HOME/.config/bspwm/key_abnt_2.sh &

# === Nitrogen (Wallpapaer)
nitrogen --restore &


# ==== WMName for JavaApps
# wmname LG3D
# bspc rule -a Screenkey manage=off
